version: "3.1"
services:
  proxy:
    image: "nginx:alpine"
    command: ["nginx", "-g", "daemon off;"]
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=reason.dev
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - reason

  reason:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: "yarn server"
    volumes:
      - ./src:/opt/app/src
      - ./webpack.config.js:/opt/app/webpack.config.js
